### ISSUE TITLE
why？

### ISSUE THREAD

**Issue by fxeavh** [IceKyrin/sovits_f0_infer#16]
PS E:\sovits_f0_infer-2.0> python flask_api.py
Traceback (most recent call last):
  File "E:\sovits_f0_infer-2.0\flask_api.py", line 46, in <module>
    svc_model = Svc(f"pth/{model_name}", f"configs/{config_name}")
  File "E:\sovits_f0_infer-2.0\sovits\infer_tool.py", line 124, in __init__
    self.hps_ms = utils.get_hparams_from_file(config_path)
  File "E:\sovits_f0_infer-2.0\sovits\utils.py", line 58, in get_hparams_from_file
    with open(config_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/config.json'

**Comment by fxeavh** [comment]
sorry i fixed that :)
